// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

/**
 * Lovable Cloud Platform integration layer.
 */
export const lovable = {
  auth: {
    /**
     * Initiates OAuth login using the specified identity provider.
     * Integrates with Lovable Cloud Auth and links the resultant token session to Supabase.
     *
     * @param {"google" | "apple" | "microsoft" | "lovable"} provider - The OAuth login provider to authenticate with.
     * @param {SignInOptions} [opts] - Optional parameters for the redirect URI and extra query parameters.
     * @returns {Promise<any>} The authentication result object, containing redirected state, token details, or error.
     */
    signInWithOAuth: async (
      provider: "google" | "apple" | "microsoft" | "lovable",
      opts?: SignInOptions,
    ) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
