import "./lib/error-capture";

import { consumeLastCapturedError } from "./lib/error-capture";
import { renderErrorPage } from "./lib/error-page";

type ServerEntry = {
  fetch: (request: Request, env: unknown, ctx: unknown) => Promise<Response> | Response;
};

let serverEntryPromise: Promise<ServerEntry> | undefined;

/**
 * Lazy loads and caches the TanStack React Start server entrypoint handler.
 *
 * @returns {Promise<ServerEntry>} A promise resolving to the server entry handler.
 */
async function getServerEntry(): Promise<ServerEntry> {
  if (!serverEntryPromise) {
    serverEntryPromise = import("@tanstack/react-start/server-entry").then(
      (m) => (m.default ?? m) as ServerEntry,
    );
  }
  return serverEntryPromise;
}

// h3 swallows in-handler throws into a normal 500 Response with body
// {"unhandled":true,"message":"HTTPError"} — try/catch alone never fires for those.
/**
 * Detects and intercepts generic 500 error responses generated by the downstream web framework (h3).
 * If the response represents a swallowed unhandled server error, it retrieves the out-of-band captured error,
 * prints it to stderr, and overrides the response body with a user-friendly custom HTML error page.
 *
 * @param {Response} response - The incoming fetch response to check.
 * @returns {Promise<Response>} A promise resolving to either the original response or a modified 500 error page response.
 */
async function normalizeCatastrophicSsrResponse(response: Response): Promise<Response> {
  if (response.status < 500) return response;
  const contentType = response.headers.get("content-type") ?? "";
  if (!contentType.includes("application/json")) return response;

  const body = await response.clone().text();
  if (!body.includes('"unhandled":true') || !body.includes('"message":"HTTPError"')) {
    return response;
  }

  console.error(consumeLastCapturedError() ?? new Error(`h3 swallowed SSR error: ${body}`));
  return new Response(renderErrorPage(), {
    status: 500,
    headers: { "content-type": "text/html; charset=utf-8" },
  });
}

/**
 * Default server-side fetch handler that routes all incoming HTTP requests.
 * Evaluates SSR components, renders client code, and falls back to a clean error page in case of crash.
 */
export default {
  /**
   * Main fetch request router for the application backend wrapper.
   *
   * @param {Request} request - The incoming HTTP Request.
   * @param {unknown} env - Global server/binding environment variable context.
   * @param {unknown} ctx - Context object mapping request context details.
   * @returns {Promise<Response>} The HTTP response to return to the requester client.
   */
  async fetch(request: Request, env: unknown, ctx: unknown) {
    try {
      const handler = await getServerEntry();
      const response = await handler.fetch(request, env, ctx);
      return await normalizeCatastrophicSsrResponse(response);
    } catch (error) {
      console.error(error);
      return new Response(renderErrorPage(), {
        status: 500,
        headers: { "content-type": "text/html; charset=utf-8" },
      });
    }
  },
};
